<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FacturadorElectronico.Aplicacion\FacturadorElectronico.Aplicacion.csproj" />
    <ProjectReference Include="..\FacturadorElectronico.Dominio\FacturadorElectronico.Dominio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ConexionDGII">
      <HintPath>..\lib\ConexionDGII.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <!--<ProjectReference Include="..\..\FacturacionElectronicaDGII-repo\ConexionDGIINETFramework.csproj" />-->
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="runtime.native.System.Security.Cryptography" Version="4.3.4" />
    <PackageReference Include="System.Security.Cryptography.Csp" Version="4.3.0" />
  </ItemGroup>
  
</Project>
